name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}] # roda todo dia
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: caioguimaraes18
          filename: metrics.isocalendar.svg

          # Plugin Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
